import Navbar from '@src/components/Navbar';
import TimeClock from '@src/components/TimeClock';
import Timer from '@src/components/Timer';
import store from '@src/store';

import Head from 'next/head';
import { Provider } from 'react-redux';

export default function Home() {
  return (
    <>
      <Head>
        <title>Notify-Me</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Provider store={store}>
        <Navbar />
        <main>
          <TimeClock />
        </main>
      </Provider>
    </>
  );
}
